{% set name = "meson" %}
{% set version = "0.49.2" %}
{% set sha256 = "a980e3f1102d42c96f8a29ed2549016539a2527d8f02b17926d3da3501fe7332" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - backport-pr-4187.patch
    - windows-reexec.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - ninja >=1.8.2

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: http://mesonbuild.com
  license: Apache 2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'The Meson Build System'
  doc_url: http://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
