{% set name = "meson" %}
{% set version = "0.58.1" %}
{% set sha256 = "3144a3da662fcf79f1e5602fa929f2821cba4eba28c2c923fe0a7d3e3db04d5d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - meson = mesonbuild.mesonmain:main

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - wheel
  run:
    - python >=3.6
    - ninja >=1.8.2
    - setuptools

test:
  requires:
    - pip
  commands:
    - pip check
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: https://mesonbuild.com
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: The Meson Build System
  doc_url: https://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
    - wolfv
    - tschoonj
