{% set name = "meson" %}
{% set version = "0.48.0" %}
{% set sha256 = "ecc6b319d86362d1ae2a64c40738f15dff5921b01cdba5d6506c877e4dd55c61" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - ninja >=1.8.2

test:
  commands:
    - meson -h
    - meson -v
    - where meson  # [win]

about:
  home: http://mesonbuild.com
  license: Apache 2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'The Meson Build System'
  doc_url: http://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - SoapZA
