{% set name = "meson" %}
{% set version = "0.53.2" %}
{% set sha256 = "3e8f830f33184397c2eb0b651ec502adb63decb28978bdc84b3558d71284c21f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # See conda-forge/glib-feedstock#40 for documentation regarding the RPATH patch
  patches:
    - 0001-Only-fix-RPATH-if-install_rpath-is-not-empty.patch
    - windows-reexec.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - meson = mesonbuild.mesonmain:main

requirements:
  host:
    - python >=3.5.2
    - setuptools
    - pip
  run:
    - python >=3.5.2
    - ninja >=1.8.2

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: http://mesonbuild.com
  license: Apache 2
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: The Meson Build System
  doc_url: http://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
