{% set name = "meson" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meson-{{ version }}.tar.gz
  sha256: 8071860c1f46a75ea34801490fd1c445c9d75147a65508cd3a10366a7006cc1c
  # See conda-forge/glib-feedstock#40 for documentation regarding the RPATH patch
  patches:
    - 0001-Only-fix-RPATH-if-install_rpath-is-not-empty.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]
  entry_points:
    - meson = mesonbuild.mesonmain:main

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - wheel
    - setuptools-scm
  run:
    - python
    - ninja-base >=1.8.2
  run_constrained:
    - ninja >=1.8.2

test:
  imports:
    - mesonbuild
    - mesonbuild.ast
    - mesonbuild.build
    - mesonbuild.cargo
    - mesonbuild.compilers
    - mesonbuild.coredata
    - mesonbuild.dependencies
    - mesonbuild.depfile
    - mesonbuild.envconfig
    - mesonbuild.environment
    - mesonbuild.interpreter
    - mesonbuild.interpreterbase
    - mesonbuild.linkers
    - mesonbuild.machinefile
    - mesonbuild.mesonlib
    - mesonbuild.mformat
    - mesonbuild.mlog
    - mesonbuild.modules
    - mesonbuild.msetup
    - mesonbuild.mtest
    - mesonbuild.optinterpreter
    - mesonbuild.options
    - mesonbuild.programs
    - mesonbuild.scripts
    - mesonbuild.templates
    - mesonbuild.wrap
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: https://mesonbuild.com
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: The Meson Build System
  description: |
    Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible.
    The main design point of Meson is that every moment a developer spends writing or debugging build definitions is a second wasted.
    So is every second spent waiting for the build system to actually start compiling code.
  doc_url: https://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  skip-lints:
    - python_build_tool_in_run  # meson is build tool that uses pip, wheel, setuptools
    - build_tools_must_be_in_build  # meson is a build tool that can use ninja
    - missing_imports_or_run_test_py  # meson does not install the meson module (done by meson-python)
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
    - wolfv
    - tschoonj
    - rgommers
    - h-vetinari
