{% set name = "meson" %}
{% set version = "0.50.1" %}
{% set sha256 = "242af7cd9088e8aeca7ff1a93e029c4d16d89880fdcf62913ad85a26bbe66316" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - windows-reexec.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  entry_points:
    - meson = mesonbuild.mesonmain:main

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - ninja >=1.8.2

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: http://mesonbuild.com
  license: Apache 2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'The Meson Build System'
  doc_url: http://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
