travis:
  secure:
    BINSTAR_TOKEN: h9IOCFYIMmcrHuuZIyhvy5eWsszRWSeZJLTIysB96KWblruXgbAUec6dTViyR66tgnPNGMOhGQk915sVFY6yX7egc5cyXSuJEmPc8rr0FycAl9UR0CmFU6XKmdqh+SCkyMCbtWAGy0AiWnykxuSZcjB6HbbRjZoFxCwoUnN2Otqa8U7R3dJ/47sarAx7icTpuwvGndPVGejjPAilmWRPNDy+Dg1flCRBUIRTIsHtU6zRzs6M6Q/RDXL91211b/S8ME+qGjFgBPil6ewucFUKJ6SkGJ9OY1+8sv2nkI8zrTbVG2C1Iy2+E5d8xY2CT0lcYSidS50jiwGaRrErJPcc48P1414/b3SEmmNj5k75SPB/jlQNBPpvp+MhvqjxC18OKWAmut9gfgBwNBKmliK444nmvwtBkFH+kWJa8L8TD4QGsP4oFp3l1oJHR/501416YIEF6YjLntzvnHN+J0LpubDVFoPUL78vT1z1ewvbHPCuFD4UKNFeGM/0gIgv1AuWiWwj5r1HK8G3CpEw28ZARWIcHrltmRT0C6kDkfr+w+MkK2VVmsf5nWCBX4yUxpfYKlvfcl6cSrbjl2pdy94W/dFivJL9ZsMwfABt4wq+JTtfQUMxOizMWrXU4p79xg91JEZzeREnRikQDmUlmxB5sBBZ1AlrafsyBC7PouuM5Z4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
